### PR TITLE
Add plugin for XH-HK4401 clone with different control codes

### PR DESCRIPTION
**Pull request by lumascet**
I bought apparently a slightly different version of the XH-HK4401 4 port kvm. It uses a shorter code for switching outputs and does not report back the switched channel if it is set via the control port. it will only report if one physical button is pressed. I altered the python code of the xh_hk4401.py and created a new h4401.py (i just made this name up, i dont think it has a model number). Now my kvm is working as indended.

Here is the store link of the kvm: https://www.aliexpress.com/item/1005005979139402.html

### CODE REVIEW

**Comment by mdevaev** [comment]
Hello. Please find some kind of marking on the case or inside on the pcb, I would not like to call the module by a random name

**Comment by lumascet** [comment]
Good point. I opened up the kvm and there are two boards with different labels.

- the HDMI switch board has the label `HK4501-V0-A1-HDMI`
- the USB/control board has the label `HK4401-V1.9-B-USB`

I think it would make more sense to use the usb board name, but thats exactly the same. Maybe the new product name is HK4501 and they just reused the older control board? What do you think?

IMG_4287
IMG_4288

**Comment by mdevaev** [comment]
Probably some kind of variation. Okay, I'll just add support for this protocol to the existing xk module.

**Comment by mdevaev** [comment]
Please test `xh_hk4401.py` from the master branch and set option `protocol: 2` in the gpio config for it.

**Comment by lumascet** [comment]
Thanks! Changes working as intended.

**Comment by mdevaev** [comment]
:ok_hand:

**Comment by mdevaev** [comment]
I will make a new release with it now.

**Pull request closed without merging**
