### PR TITLE
add target all so build can be easly checked

### PR DESCRIPTION
**Pull request by tomaszduda23**

### CODE REVIEW

**Comment by mdevaev** [comment]
Only one target can be assembled at a time, as this leaves an `.current` file artifact. If you want to do this just for testing, then let's do something like this:
```Makefile
_build:
        ...
_build_all: serial spi aum
        rm -f .current
```

**Comment by tomaszduda23** [comment]
done

**Comment by mdevaev** [comment]
Perfect

**Comment by tomaszduda23** [comment]
https://github.com/pikvm/kvmd/pull/90

**Pull request merged**
