### PR TITLE
fix compile warnings

### PR DESCRIPTION
**Pull request by No0ne**

### CODE REVIEW

**Comment by mdevaev** [comment]
Thanks!

**Comment by mdevaev** [comment]
I'm merging ps2-ng branch to master.

**Comment by No0ne** [comment]
Thanks! You may also delete this branch as I can submit bugfixes to master now.

**Comment by mdevaev** [comment]
Yep, and first bugfix is already required :) https://github.com/pikvm/kvmd/actions/runs/10119090495/job/27986974334

**Comment by mdevaev** [comment]
Nvm, everything is ok.

**Pull request merged**
