### PR TITLE
Scaling video through window resize and full screen mode

### PR DESCRIPTION
**Pull request by arykov**
Implementation of #14

### CODE REVIEW

**Comment by arykov** [comment]
Implemented:
- scaling through resizing
- full screen mode
- keyboard locking
- maximize window to occupy all the space below nav menu(useful if the window ran away or is outside of the screen). Otherwise need to use zoom of the browser

Got rid of the scale slider and "auto resize" check box.

**Comment by arykov** [comment]
Will look at eslint related problems on Monday

**Comment by mdevaev** [comment]
I've finally sorted out the new release and now I'll look at your PRs. Sorry for the delay.
In the meantime, I would like to ask you to pay attention to the coding style. I name variables using _, and functions using camelCase.

**Comment by arykov** [comment]
Fixed issues pointed out by es-lint and whitespace. Had a brief look at the diff and didn't see any camel, underscore violations(unless I missed any).

**Comment by mdevaev** [comment]
Bueno. Reviewing it.

**Comment by mdevaev** [comment]
Due to the workload of the v3 board I don't have time to test this change properly :( I will merge this into a separate branch and work on it as I have time. Sorry about that. But I promise it won't stay in the eternal brunch.

**Pull request merged**
