### PR TITLE
add support for Anel NET-PwrCtrl ADV as GPIO

### PR DESCRIPTION
**Pull request by PSc-secunet**
This add support for[ Anel NET-PwrCtrl ADV 8x ](https://de.anel.eu/?src=produkte/home/home.htm)switchable sockets as GPIO driver.

### CODE REVIEW

**Comment by mdevaev** [comment]
Thanks. I'll review and merge it.

**Comment by mdevaev** [comment]
Do you plan to add some documentation for this to https://github.com/pikvm/pikvm ?

**Comment by PSc-secunet** [comment]
Sorry, here you are https://github.com/pikvm/pikvm/pull/959

**Comment by mdevaev** [comment]
Thank you

**Comment by mdevaev** [comment]
I'm going to rewrite some code of this plugin. I will inform you about the changes here: #959

**Pull request merged**
