### PR TITLE
Introduce multi type HID

### PR DESCRIPTION
**Pull request by JeWe37**
This introduces the ability to have different HID plugins acting as the keyboard and mouse respectively via a `multi` plugin that dispatches to the correct HID plugin. 

This properly resolves pikvm/pikvm#1291

### CODE REVIEW

**Comment by mdevaev** [comment]
Sup. I like the approach, but I don't like magic inside otg plugin to support multihid. I can take this into a separate branch and redo something according to my understanding of how it should be, and you will test the result. What do you say?

**Comment by JeWe37** [comment]
Sure I don't mind, go ahead. I won't be able to test for the next few days though, but will get back to this after.

**Comment by mdevaev** [comment]
Good. Okay, I'll run linters on your code, please fix all errors and warning before merging.

**Comment by JeWe37** [comment]
I think that should be all the linter issues fixed.

**Comment by mdevaev** [comment]
Let's rerun checks then.

**Comment by JeWe37** [comment]
Looks fine except for one issue in pylint, but I didn't even touch the function it's complaining about?

**Comment by mdevaev** [comment]
It's a false-positive in the new pylint release. I've fixed it.

**Comment by mdevaev** [comment]
JFYI I don't forget about it. Sorry for the delay, I have a very priority task right now.

**Pull request merged**
