### PR TITLE
Storage

### PR DESCRIPTION
**Pull request by tomaszduda23**
https://github.com/pikvm/kvmd/pull/90

### CODE REVIEW

**Comment by mdevaev** [comment]
In main.cpp there was an error, read_block was executed instead of update_block.

**Comment by mdevaev** [comment]
Btw are you testing the firmware after the changes?

**Comment by tomaszduda23** [comment]
I was just moving files around so didn't test those changes.

**Comment by mdevaev** [comment]
I don't mind but I have no time to do it.

**Pull request merged**
