### PR TITLE
added ssl in test mode

### PR DESCRIPTION
**Pull request by arykov**
Adds ssl, although does not force it in test mode(when running using make run). So you can access using SSL on 8443 or no SSL on 8080
Rationale: certain browser functionality(for example keyboard lock api) is only available over SSL.

### CODE REVIEW

**Comment by arykov** [comment]
Jumped the gun. Broke http

**Comment by arykov** [comment]
Http should be working now

**Comment by mdevaev** [comment]
The new kernel release with critical fixes was released today, so now I will make bugfixes and build a new version. This change will be included in the next.

**Comment by mdevaev** [comment]
Okay, I tried to implement it differently. To generate certificates, I used the kvmd-gencert script (extra testing) and did without editing nginx.conf in the repository. It seems to be working well now. Thank you for coming up with these ideas.

**Comment by mdevaev** [comment]
UPD: https://github.com/pikvm/kvmd/commit/923320da5f87d6081824641468b3777d7f1e811f

**Pull request closed without merging**
