### PR TITLE
Check that a packet start with PROTO::MAGIC

### PR DESCRIPTION
**Pull request by McNova**

### CODE REVIEW

**Comment by mdevaev** [comment]
Why we need this?

**Comment by McNova** [comment]
Because uart communication isn't packet and there is no warranty that client receive everything. If we miss some byte at the beginning then the client start receiving at an offset, after 8 bytes it will be sent to handlerequest and rejected because checksum don't match. And we'll get another offseted 8 bytes and reject again and again. I discovered that trying to port the protocol to micropyhton.

**Comment by mdevaev** [comment]
I see, thanks. Now I need to review full protocol logic on the both sides. Jfyi.

**Comment by mdevaev** [comment]
Sorry for the long answer. If a byte was lost, a timeout should be triggered and synchronization should occur. Have you encountered a problem for which this patch is needed?

**Comment by mdevaev** [comment]
I will accept this PR, but I will comment on it, because I would like to get information about how you stumbled upon this and why timeout did not solve the problem.

**Pull request merged**
