### PR TITLE
pico hid: ps/2 keyboard support getting started

### PR DESCRIPTION
**Pull request by No0ne**

### CODE REVIEW

**Comment by mdevaev** [comment]
Could you rebase it with `master` branch? The `picohid` was already merged.

**Comment by No0ne** [comment]
sorry don't know how to do that
I did a rebase locally but on github it looks the same

**Comment by mdevaev** [comment]
Try to change the target branch from `picohid` to `master`.

**Comment by mdevaev** [comment]
UPD: did this already, take a look.

**Comment by mdevaev** [comment]
So, you want to copy all the code? Without library? Or it's just for testing?

**Comment by No0ne** [comment]
I'll just try getting started with this, maybe will extract it later.

**Comment by mdevaev** [comment]
Okay, so let me create `ps2` branch for you. Please send PRs to it.

**Comment by No0ne** [comment]
Cool thanks, thats why I thought i should merge it to picohid but a ps2 branch is better :)

**Comment by mdevaev** [comment]
Btw, maybe you want to join to our discord? We have dev channel for such
discussions. Maybe we'll work faster using it.

Пн, 14 авг. 2023 г. в 09:36, No0ne ***@***.***>:

**Pull request merged**
