### PR TITLE
PWAY plugin fix: Normalize pin/channel index to 0-based

### PR DESCRIPTION
**Pull request by kyounger**
The previous commit to this accidentally broke it. The awkwardness with this KVM switch's serial port communication is that the commands to switch the port are 1-based index (e.g. `PS 1` or `PS 15` for ports 1 or 15), but the switch reports which port is active with a 0-based index (`VGA_SWITCH_CONTROL=0` or `VGA_SWITCH_CONTROL=14`, respectively). This normalizes those indexes again.

I also adjusted the "reset" to use that method name explicitly. At the moment just sending `PS` resets the switch to port 1. The send channel method was a little confusing on that part.

### CODE REVIEW

**Comment by kyounger** [comment]
My override.yaml I used to test this:

```
kvmd:
    gpio:
        drivers:
            pw:
                type: pway
                device: /dev/ttyUSB0
        scheme:
            ch1_led:
                driver: pw
                pin: 1
                mode: input
            ch2_led:
                driver: pw
                pin: 2
                mode: input
            ch3_led:
                driver: pw
                pin: 3
                mode: input
            ch4_led:
                driver: pw
                pin: 4
                mode: input
            ch5_led:
                driver: pw
                pin: 5
                mode: input
            ch6_led:
                driver: pw
                pin: 6
                mode: input
            ch7_led:
                driver: pw
                pin: 7
                mode: input
            ch8_led:
                driver: pw
                pin: 8
                mode: input
            ch9_led:
                driver: pw
                pin: 9
                mode: input
            ch10_led:
                driver: pw
                pin: 10
                mode: input
            ch11_led:
                driver: pw
                pin: 11
                mode: input
            ch12_led:
                driver: pw
                pin: 12
                mode: input
            ch13_led:
                driver: pw
                pin: 13
                mode: input
            ch14_led:
                driver: pw
                pin: 14
                mode: input
            ch15_led:
                driver: pw
                pin: 15
                mode: input
            ch16_led:
                driver: pw
                pin: 16
                mode: input
            ch1_button:
                driver: pw
                pin: 1
                mode: output
                switch: false
            ch2_button:
                driver: pw
                pin: 2
                mode: output
                switch: false
            ch3_button:
                driver: pw
                pin: 3
                mode: output
                switch: false
            ch4_button:
                driver: pw
                pin: 4
                mode: output
                switch: false
            ch5_button:
                driver: pw
                pin: 5
                mode: output
                switch: false
            ch6_button:
                driver: pw
                pin: 6
                mode: output
                switch: false
            ch7_button:
                driver: pw
                pin: 7
                mode: output
                switch: false
            ch8_button:
                driver: pw
                pin: 8
                mode: output
                switch: false
            ch9_button:
                driver: pw
                pin: 9
                mode: output
                switch: false
            ch10_button:
                driver: pw
                pin: 10
                mode: output
                switch: false
            ch11_button:
                driver: pw
                pin: 11
                mode: output
                switch: false
            ch12_button:
                driver: pw
                pin: 12
                mode: output
                switch: false
            ch13_button:
                driver: pw
                pin: 13
                mode: output
                switch: false
            ch14_button:
                driver: pw
                pin: 14
                mode: output
                switch: false
            ch15_button:
                driver: pw
                pin: 15
                mode: output
                switch: false
            ch16_button:
                driver: pw
                pin: 16
                mode: output
                switch: false
        view:
            table:
                - ["#Host 1", ch1_led, ch1_button]
                - ["#Host 2", ch2_led, ch2_button]
                - ["#Host 3", ch3_led, ch3_button]
                - ["#Host 4", ch4_led, ch4_button]
                - ["#Host 5", ch5_led, ch5_button]
                - ["#Host 6", ch6_led, ch6_button]
                - ["#Host 7", ch7_led, ch7_button]
                - ["#Host 8", ch8_led, ch8_button]
                - ["#Host 9", ch9_led, ch9_button]
                - ["#Host 10", ch10_led, ch10_button]
                - ["#Host 11", ch11_led, ch11_button]
                - ["#Host 12", ch12_led, ch12_button]
                - ["#Host 13", ch13_led, ch13_button]
                - ["#Host 14", ch14_led, ch14_button]
                - ["#Host 15", ch15_led, ch15_button]
                - ["#Host 16", ch16_led, ch16_button]
```

**Comment by mdevaev** [comment]
I would prefer not to do this, since in all other plugins the starting point of numbering is 0

**Comment by kyounger** [comment]
`pin` is really a misnomer here. There are no pins, just port numbers. But if there is some consistency to be realized, then I can push another commit that normalizes this to 0-based.

**Comment by kyounger** [comment]
Ok, I pushed the commit. This is the override.yaml I used (just decremented all the pins):

```
kvmd:
    gpio:
        drivers:
            pw:
                type: pway
                device: /dev/ttyUSB0
        scheme:
            ch1_led:
                driver: pw
                pin: 0
                mode: input
            ch2_led:
                driver: pw
                pin: 1
                mode: input
            ch3_led:
                driver: pw
                pin: 2
                mode: input
            ch4_led:
                driver: pw
                pin: 3
                mode: input
            ch5_led:
                driver: pw
                pin: 4
                mode: input
            ch6_led:
                driver: pw
                pin: 5
                mode: input
            ch7_led:
                driver: pw
                pin: 6
                mode: input
            ch8_led:
                driver: pw
                pin: 7
                mode: input
            ch9_led:
                driver: pw
                pin: 8
                mode: input
            ch10_led:
                driver: pw
                pin: 9
                mode: input
            ch11_led:
                driver: pw
                pin: 10
                mode: input
            ch12_led:
                driver: pw
                pin: 11
                mode: input
            ch13_led:
                driver: pw
                pin: 12
                mode: input
            ch14_led:
                driver: pw
                pin: 13
                mode: input
            ch15_led:
                driver: pw
                pin: 14
                mode: input
            ch16_led:
                driver: pw
                pin: 15
                mode: input
            ch1_button:
                driver: pw
                pin: 0
                mode: output
                switch: false
            ch2_button:
                driver: pw
                pin: 1
                mode: output
                switch: false
            ch3_button:
                driver: pw
                pin: 2
                mode: output
                switch: false
            ch4_button:
                driver: pw
                pin: 3
                mode: output
                switch: false
            ch5_button:
                driver: pw
                pin: 4
                mode: output
                switch: false
            ch6_button:
                driver: pw
                pin: 5
                mode: output
                switch: false
            ch7_button:
                driver: pw
                pin: 6
                mode: output
                switch: false
            ch8_button:
                driver: pw
                pin: 7
                mode: output
                switch: false
            ch9_button:
                driver: pw
                pin: 8
                mode: output
                switch: false
            ch10_button:
                driver: pw
                pin: 9
                mode: output
                switch: false
            ch11_button:
                driver: pw
                pin: 10
                mode: output
                switch: false
            ch12_button:
                driver: pw
                pin: 11
                mode: output
                switch: false
            ch13_button:
                driver: pw
                pin: 12
                mode: output
                switch: false
            ch14_button:
                driver: pw
                pin: 13
                mode: output
                switch: false
            ch15_button:
                driver: pw
                pin: 14
                mode: output
                switch: false
            ch16_button:
                driver: pw
                pin: 15
                mode: output
                switch: false
        view:
            table:
                - ["#Host 1", ch1_led, ch1_button]
                - ["#Host 2", ch2_led, ch2_button]
                - ["#Host 3", ch3_led, ch3_button]
                - ["#Host 4", ch4_led, ch4_button]
                - ["#Host 5", ch5_led, ch5_button]
                - ["#Host 6", ch6_led, ch6_button]
                - ["#Host 7", ch7_led, ch7_button]
                - ["#Host 8", ch8_led, ch8_button]
                - ["#Host 9", ch9_led, ch9_button]
                - ["#Host 10", ch10_led, ch10_button]
                - ["#Host 11", ch11_led, ch11_button]
                - ["#Host 12", ch12_led, ch12_button]
                - ["#Host 13", ch13_led, ch13_button]
                - ["#Host 14", ch14_led, ch14_button]
                - ["#Host 15", ch15_led, ch15_button]
                - ["#Host 16", ch16_led, ch16_button]
```

**Comment by kyounger** [comment]
Though, if you plan to squash, the commit message will need to be amended. Happy to do that and force push if you'd prefer.

**Comment by kyounger** [comment]
Once this is finalized, I can also help get docs together. I know @SpookHCK has been busy. I have been tinkering more with mine lately and found some additional commands I think are worth documenting, alongside how to build out the USB-to-Serial connection to the device and test it.

**Pull request merged**
