### PR TITLE
Added driver for xh_hk4401 4 port HDMI/USB KVM

### PR DESCRIPTION
**Pull request by ep1cman**
Adds support for the "XH-HK4401" HDMI/USB KVM (e.g: https://www.aliexpress.com/item/1005002857996898.html?spm=a2g0o.productlist.0.0.4848c2c8M4keuc&algo_pvid=f1b52ddf-b577-4d45-bd56-0ad71ba4c5ba&algo_exp_id=f1b52ddf-b577-4d45-bd56-0ad71ba4c5ba-11&pdp_ext_f=%7B%22sku_id%22%3A%2212000023066118566%22%7D)

Requires inverters or a UART adapter that can do signal inversion to work. I will follow this up with a documentation PR to the main PiKVM repo to explain the setup.

### CODE REVIEW

**Comment by ep1cman** [comment]
Considering how similar the code is for the UART based KVMs it might be worth making a base class for them

**Comment by mdevaev** [comment]
Pleas make channel range is `0...3` for consistency with other plugins.

**Comment by mdevaev** [comment]
Thanks. I'll fix the rest myself. Where did you find the model number for the module name?

**Comment by ep1cman** [comment]
Its written on the PCBs inside, and if you google it a couple listings appear for the same KVM.

**Pull request merged**
