### PR TITLE
Keyboard

### PR DESCRIPTION
**Pull request by tomaszduda23**
https://github.com/pikvm/kvmd/pull/90

### CODE REVIEW

**Comment by mdevaev** [comment]
I was going to merge this, but saw a conflict. To make new PRS, you need to wait for the old ones. I also noticed problems with using spaces instead of tabs and other little things with the coding style (I have a bit specific, sorry). How much will I complicate your work if I make corrections now, before you do rebase?

**Comment by tomaszduda23** [comment]
It would be nice if you force code style by CI or pre-commit hook https://github.com/pikvm/pikvm/issues/772
> other little things with the coding style (I have a bit specific, sorry).

I'm not sure what you mean here

**Comment by mdevaev** [comment]
I don't know if I have the patience to set up a linter :)

**Comment by mdevaev** [comment]
Commited refactoring, please take a look: https://github.com/pikvm/kvmd/commit/ad6a387941012e5c54b1f6e977e4bc5425f9be5d

**Comment by tomaszduda23** [comment]
I will try to follow but sometime it is not so obvious what is the rule :]

**Comment by mdevaev** [comment]
Yea, sorry. But it's not difficult for me to refactor after your next PR.

**Comment by tomaszduda23** [comment]
If you can refactor I'm fine to rebase.

**Pull request merged**
