### PR TITLE
(window.css): correct window border behavior

### PR DESCRIPTION
**Pull request by ly4096x**
prevent window size change between active/inactive.
enable borderless full screen mode.

### CODE REVIEW

**Comment by ly4096x** [comment]
Looks like removing the border is creating a mouse position glitch by 1px. Need help on this. Thanks.

**Comment by ly4096x** [comment]
Resolved. It's not a problem of changing border, but a problem that has always been there. Centering the local cursor resolves this.

**Comment by mdevaev** [comment]
I would prefer to keep the blue border as sometimes the window can lose focus even in full-screen mode. As for the cursor - this is a good change, let's merge just that.

**Comment by ly4096x** [comment]
I agree that the border can be useful in your case. For me I always use a dual monitor setup so that was not a problem for me. I can try to find a way to keep the border but stop window resizing when getting focus. What to you think?

**Comment by mdevaev** [comment]
Good idea.

**Comment by mdevaev** [comment]
I took the coordinate correction from here and made the blue dot transparent. If you find a way to fix the screen frame, please make another PR.

**Pull request closed without merging**
