### PR TITLE
zh_CN translate

### PR DESCRIPTION
**Pull request by wnark**
Tentative Chinese translation

### CODE REVIEW

**Comment by mdevaev** [comment]
Wait, did you localize HTML files, not PUG?

**Comment by wnark** [comment]
Yes, I just translated the html and just need overwrite the web folder. (I'm lazy and don't want to overwrite files one by one)

**Comment by mdevaev** [comment]
You had to copy and edit the PUG files from which the HTML is generated.
For example: https://github.com/pikvm/kvmd/blob/master/web/index.pug

**Comment by mdevaev** [comment]
I'm sorry, but I can't apply it in this form.

**Pull request closed without merging**
